version: '3.9'

services:
  pgmaster:
    container_name: "pgmaster"
    image: "postgres:16.1-alpine"
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "./volumes/pgmaster/:/var/lib/postgresql/data"
    ports:
      - "15431:5432"

  pgslave:
    container_name: "pgslave"
    image: "postgres:16.1-alpine"
    networks:
      - pgnet
    ports:
      - "15432:5432"
    volumes:
      - "./volumes/pgslave/:/var/lib/postgresql/data"
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  pgslaveasync:
    container_name: "pgslaveasync"
    image: "postgres:16.1-alpine"
    networks:
      - pgnet
    ports:
      - "15433:5432"
    volumes:
      - "./volumes/pgslaveasync/:/var/lib/postgresql/data"
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  pgadmin:
    container_name: "pgadmin4_container"
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"

  social-network:
    build:
      dockerfile: Dockerfile
    container_name: "social-network-server"
    environment:
#      JWT_KEY: $JWT_KEY
#      DB_HOST: $DB_HOST
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
    ports:
      - "8080:8080"
    depends_on:
      - pgmaster

  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
networks:
  pgnet:
  monitoring: